version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: shaiya_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shaiya_game
      POSTGRES_USER: shaiya
      POSTGRES_PASSWORD: shaiya123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Montar migraciones para ejecución automática si es necesario
      # - ./migrations/migrations:/docker-entrypoint-initdb.d
    networks:
      - shaiya_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shaiya -d shaiya_game"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # PgAdmin (opcional para administración)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: shaiya_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shaiya.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - shaiya_network
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - admin

volumes:
  postgres_data:
    name: shaiya_postgres_data
  pgadmin_data:
    name: shaiya_pgadmin_data

networks:
  shaiya_network:
    name: shaiya_network
    driver: bridge
